# SonarCloud (організація та проєкт).
sonar.organization=olesiashn3
sonar.projectKey=olesiashn3_uniflow

sonar.host.url=https://sonarcloud.io

sonar.sources=app
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
